apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: ghcr.io/mikejohnpp/ai-service:ba7bebc889f97a0519d4da35fc0c81f4ee0d2d7a
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "final-graduate-cluster-kafka-bootstrap.kafka:9092"
            - name: KAFKA_GROUP_ID
              value: "ai-service-group"
            - name: KAFKA_TOPICS
              value: "post.analyze.sentiment"
            - name: KAFKA_OUTPUT_TOPIC
              value: "post.analyze.result"
            - name: MODEL_DIR
              value: "/app/data"
            - name: MODEL_REPO_ID
              value: "MikeJohnP/HTC_ImplicitSentiment"
            - name: HF_HOME
              value: "/app/data"
            - name: DEVICE
              value: "cpu"
            - name: MODEL
              value: "htc"
            - name: MAX_LEN
              value: "40"
          volumeMounts:
            - name: ai-service-volume
              mountPath: /app/data
      volumes:
        - name: ai-service-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: default
spec:
  selector:
    app: ai-service
  ports:
    - port: 3000
      targetPort: 8080
  type: ClusterIP
