apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      # imagePullSecrets:
      #   - name: ghcr-secret
      containers:
        - name: chat-service
          image: ghcr.io/mikejohnpp/chat-service:4e2114753fd628f55ba9c4ec4a16b2b27af0b421
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: default
spec:
  selector:
    app: chat-service
  ports:
    - port: 3000
      targetPort: 8080
  type: ClusterIP
