apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      # imagePullSecrets:
      #   - name: ghcr-secret
      containers:
        - name: chat-service
          image: ghcr.io/mikejohnpp/chat-service:106e143c7b0ec65eae3cfb3565a81d6fa867568e
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "jdbc:mysql://mysql-service/FinalGraduateDB?zeroDateTimeBehavior=convertToNull"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: ""
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "default"
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: default
spec:
  selector:
    app: chat-service
  ports:
    - port: 3000
      targetPort: 8080
  type: ClusterIP
