apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      # imagePullSecrets:
      #   - name: ghcr-secret
      containers:
        - name: auth-service
          image: ghcr.io/mikejohnpp/auth-service:198b18b07656cb4becd7c0b5a0d508beca58b55d
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_URL
              value: "jdbc:mysql://mysql-service/FinalGraduateDB?zeroDateTimeBehavior=convertToNull"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: ""
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
spec:
  selector:
    app: auth-service
  ports:
    - port: 3000
      targetPort: 8080
  type: ClusterIP
