apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessor-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocessor-service
  template:
    metadata:
      labels:
        app: preprocessor-service
    spec:
      # imagePullSecrets:
      #   - name: ghcr-secret
      containers:
        - name: preprocessor-service
          image: ghcr.io/mikejohnpp/preprocessor-service:42a50ea93b856206459c13d1bd49ad029c5cd1bc
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: preprocessor-service
  namespace: default
spec:
  selector:
    app: preprocessor-service
  ports:
    - port: 3000
      targetPort: 8080
  type: ClusterIP
