apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessor-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocessor-service
  template:
    metadata:
      labels:
        app: preprocessor-service
    spec:
      # imagePullSecrets:
      #   - name: ghcr-secret
      containers:
        - name: preprocessor-service
          image: ghcr.io/mikejohnpp/preprocessor-service:c24c95563c8e6918dc8d52fa52575aa1a846177e
      #    ports:
      #      - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "final-graduate-cluster-kafka-bootstrap.kafka:9092"
            - name: KAFKA_GROUP_ID
              value: "preprocessor-service-group"
            - name: KAFKA_TOPICS
              value: "post.analyze.preprocessor"
            - name: KAFKA_OUTPUT_TOPIC
              value: "post.analyze.sentiment"
            - name: KAFKA_RESULT_TOPIC
              value: "post.analyze.result"
            - name: MIN_COMMIT_COUNT
              value: "1"
            - name: CORENLP_DIR
              value: "/app/data/preprocessor"
            - name: SRL_API_URL
              value: "http://srl-service:3000/predict"

          volumeMounts:
            - name: preprocessor-service-volume
              mountPath: /app/data/preprocessor
      volumes:
        - name: preprocessor-service-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: preprocessor-service
#  namespace: default
#spec:
#  selector:
#    app: preprocessor-service
#  #ports:
#    #- port: 3000
#    #  targetPort: 8080
#  type: ClusterIP
