apiVersion: apps/v1
kind: Deployment
metadata:
  name: srl-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srl-service
  template:
    metadata:
      labels:
        app: srl-service
    spec:
      # imagePullSecrets:
      #   - name: ghcr-secret
      nodeSelector:
        kubernetes.io/hostname: worker-3.k8s
      containers:
        - name: srl-service
          image: ghcr.io/mikejohnpp/srl-service:c84917485e9db5e1f50d303d498d5e768f77e8b3
          ports:
            - containerPort: 8080
          env:
            - name: ALLENNLP_CACHE_ROOT
              value: "/app/data/srl"
            - name: MODEL_URL
              value: "https://storage.googleapis.com/allennlp-public-models/structured-prediction-srl-bert.2020.12.15.tar.gz"
            - name: CUDE_DEVICE
              value: "-1"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8080"

          volumeMounts:
            - name: srl-service-volume
              mountPath: /app/data/srl
      volumes:
        - name: srl-service-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: srl-service
  namespace: default
spec:
  selector:
    app: srl-service
  ports:
    - port: 3000
      targetPort: 8080
  type: ClusterIP
